### ISSUE TITLE
About cross-domain

### ISSUE THREAD

**Issue by drickzsy** [guidonguido/DA_detection#1]
Hi author!
May I ask the question about where is your cross-domain operation? And do you have a paper related to this code? 

Thank you!

**Comment by guidonguido** [comment]
Hi!
This was a university project. I can't help you with code explanation.

However, here is the related paper.

[university_report_project.pdf](https://github.com/guidonguido/DA_detection/files/7846648/s252865_s279127_s265651_report_project.pdf)
